refactor: move vsphere account under auth to match new plugin api
validator-labs/validatorctl pull request #189
Opened 2024-08-22 20:31 UTC by arturshadnik

## Issue
Resolves #183 

## Description
Removing `VspherePluginConfig.Account` and switching to using `.Auth.CloudAccount`, to align with updates to the plugin.

2024-08-22 20:55 UTC, ahmad-ibra approved these changes
LGTM

2024-08-22 20:57 UTC, TylerGillson requested changes

2024-08-22 20:57 UTC, TylerGillson commented on pkg/utils/embed/resources/validator/validator-base-values.tmpl
>    {{- if .VspherePlugin.Validator.Auth.SecretName }}
You can DRY this:

```
  vSphere:
  {{- if .VspherePlugin.Validator.Auth.SecretName }}
    secretName: {{ .VspherePlugin.Validator.Auth.SecretName }}
  {{- end }}
  username ...
  ...
```

2024-08-22 21:18 UTC, TylerGillson approved these changes

2024-08-23 18:06 UTC, TylerGillson approved these changes

2024-08-23 18:57 UTC, merged